### ISSUE TITLE
Please publish the newest version of gz-transport-sys to crates.io

### ISSUE THREAD

**Issue by ViliamVadocz** [eduidl/gz-rs#9]
I was not able to compile because I got this `Error: "gz-transport or ignition-transport not found"`, but when I tried cloning this repository and using a path dependency instead it worked.

I think you forgot to publish the newest version of the build script for `gz-transport-sys` to crates.io.

**Comment by eduidl** [comment]
I have some questions.

1. What version of gazebo did you install?
2. Is pkg-config is installed? If no, would you install it and retry.

**Comment by ViliamVadocz** [comment]
1. Gazebo Harmonic `13.0.0`
2. Yes it is

The code you have on `main` works. It just looks like you made changes to the crate but didn't publish the newest version to crates.io.

**Comment by ViliamVadocz** [comment]
This doesn't work:
```toml
[dependencies]
gz-msgs = { version = "0.6.0", default-features = false, features = [
    "harmonic",
] }
gz = "0.6.0"
```

This works:
```toml
[dependencies]
gz-msgs = { git = "https://github.com/eduidl/gz-rs", default-features = false, features = [
    "harmonic",
] }
gz = { git = "https://github.com/eduidl/gz-rs" }
```

I would prefer to use the crates.io versions instead of relying on `git`.
